### PR TITLE
Fix false positives for component in `prefer-class-directive` rule

### LINKED ISSUE #176: `prefer-class-directive` should be ignored on a component
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.19.0

### What version of `eslint-plugin-svelte` are you using?

2.1.0

### What did you do?

As mentioned in https://github.com/ota-meshi/eslint-plugin-svelte/issues/173 a reminder to fix a similar issue for `prefer-class-directive`.

### What did you expect to happen?

.

### What actually happened?

.

### Link to Minimal Reproducible Example

.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by ota-meshi**
fixes #176

### CODE REVIEW

**Review by JounQin — APPROVED** [review]

File: src/utils/ast-utils.ts [hunk 1]
```diff
@@ -98,6 +98,28 @@ export function needParentheses(
...
+  node:
+    | SvAST.SvelteElement
+    | SvAST.SvelteScriptElement
+    | SvAST.SvelteStyleElement,
+): node is
+  | SvAST.SvelteHTMLElement
+  | (SvAST.SvelteSpecialElement & {
+      name: SvAST.SvelteName & { name: "svelte:element" }
+    }) {
+  if (node.type === "SvelteElement") {
```
Comment (JounQin) [inline src/utils/ast-utils.ts:112]: How about `return` earlier?

```ts
if (node.type !== 'SvelteElement') {
  return false
}

if (node.kind === 'html') {
  return true
}
if (node.kind === 'special') {
  return node.name.name === 'svelte:element'
}
```

Comment (ota-meshi) [reply src/utils/ast-utils.ts:112]: That's good! I change to use it.

**Review by JounQin — APPROVED** [review]

**Comment by ota-meshi** [comment]
Thank you for your review!
